name: expense_management_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  retrofit: ^4.4.2
  hive: ^2.2.3
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  firebase_storage: ^12.4.4
  connectivity_plus: ^6.1.3
  fl_chart: ^0.70.2
  firebase_messaging: ^15.2.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.9
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpe

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
